   export const EventData= [{
        "id": 1,
        "name": "Blind Fold Typing",
        "description": "The biggest benefit of blindfolded activities is that it develops skills and improves typing speed.",
       "description1": "An event that tests your communication and typing skills. Accuracy speed and precision mixes along with listening skills matter.",
       "description2":"The typing player's computer display will remain off.",
       "description3":"Points will be awarded based on the accuracy and speed of the typed sentence. Points will be deducted for any errors or typos.",
        "entry": 50,
        "wining": "800/-",
        "category": "technical",
        "coordinator": "Nisha vishwakarma [9926800217] ",
       "coordinator1":"Mahak yadav [7223866797]",
       "coordinator2":"Nilesh vishwakarma [8817044261]",
       "coordinator3":"Abhijit Alat [6260112097]",
       "register":"RegisterLink"
    },
       {
           "id": 2,
           "name": "Art of Web",
           "description": "The “Art of Web” is basically the competition of making or designing The landing page in \n" +
               "which we provide a topic like “ Opening of new shop “ and participates have to make a landing page \n" +
               "on this topic. Whose landing page is attractive they will win the price. ",
           "description1": "If your participation will low then event will be cancel",
           "description2":"At the time of registration you have to pay free",
           "description3":"Do not Misbehave with any Coordinator and Volunteers. \n" +
               " Do not damage Computer System otherwise you have to pay fine",
           "entry": 50,
           "wining": "1000/-",
           "category": "technical",
           "coordinator": "Prajwal Bharambe - 9009346687 ",
           "coordinator1":"Krishna Patel – 8103011226",
           "coordinator2":"Pratham Karma - 6268349828",
           // "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 3,
           "name": "Code War in C++",
           "description": "Coding Mania will be a thrilling two-round competition designed to test our programming skills using C++.\n" ,
           "description1": "The first round will focus on problem-solving, and the second round will challenge participants to find\n" ,
           "description2":"\"errors or debug code written in C++.\"",
           "description3":"The coding competition will be conducted on the systems provided by the college in computer lab",
           "entry": 50,
           "wining": "1000/-",
           "category": "technical",
           "coordinator": ": Aniket (9111510019) ",
           "coordinator1":"Aryan(6267670037)",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 4,
           "name": "Robo Race",
           "description": "If the robot by any chances falls from the" +
               "track, the robot will be kept back to the" +
               "previous checkpoint crossed with a penalty",
           "description1": "A total of 5 minutes run time (arena time)" +
               "will be given to every participant",
           "description2":"The second attempt will be on request" +
               "of the participant and consent of the judge",
           "description3":"The better of 2 scores will be considered" +
               "as final",
           "entry": 50,
           "wining": "1000/-",
           "category": "technical",
           "coordinator": "Pawan Yadav [8269667803] ",
           "coordinator1":"Priyanshu Adalak [7723951965]",
           "coordinator2":"Prakash Sharma [9301638632]",
           "coordinator3":"Jayant Nagoriya [6263122077]",
           "register":"RegisterLink"
       },
       {
           "id": 5,
           "name": "Escape Room",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 50,
           "wining": "1000/-",
           "category": "technical",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 6,
           "name": "Line Follower",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 50,
           "wining": "500/-",
           "category": "technical",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 7,
           "name": "CAD Competition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 30,
           "wining": "300/-",
           "category": "civilMe",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },{
           "id": 8,
           "name": "Aakriti Architects",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 50,
           "wining": "500/-",
           "category": "civilMe",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 9,
           "name": "Science Exhibition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 30,
           "wining": "300/-",
           "category": "civilMe",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 10,
           "name": "Mecha Archery",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 30,
           "wining": "300/-",
           "category": "civilMe",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 11,
           "name": "Khatron ke Khiladi",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 50,
           "wining": "1000/- for Boys & Girl",
           "category": "NonTech",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 12,
           "name": "Gully Cricket",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "Boys-120/- & Girls-60",
           "wining": "1200/- for Boys & 600/- for Girls",
           "category": "NonTech",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 13,
           "name": "Arm Wrestling",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "300/-",
           "category": "NonTech",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },{
           "id": 14,
           "name": "Bus Pulling",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 120,
           "wining": "1100/-",
           "category": "NonTech",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 15,
           "name": "Treasure Hunt",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 200,
           "wining": "1200/-",
           "category": "NonTech",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 16,
           "name": "Thug of War",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 40,
           "wining": "500/-",
           "category": "NonTech",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 17,
           "name": "Angry Bird",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "300/-",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 18,
           "name": "Ladder Legend",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "300/-",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 19,
           "name": "Sath Nibhana Sathiya",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 30,
           "wining": "300/-",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 20,
           "name": "Ring Ring Ringa",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 10,
           "wining": "300/-",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 21,
           "name": "Kick on OX",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "300/-",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 22,
           "name": "Bacch ke Rehna",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 23,
           "name": "Rolling Tyre",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },{
           "id": 24,
           "name": "Bouncing Ball",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 25,
           "name": "Hand and Feet Hopscotch",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 26,
           "name": "Rolling Tyre",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 27,
           "name": "Kya Tumhe Yaad h",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 28,
           "name": "Catch the Ball",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 29,
           "name": "Mard ko Dard nhi Hota",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 30,
           "name": "Target Dot",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 31,
           "name": "Glass Pyaramid",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 32,
           "name": "Blow a Ballon",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "OneShot",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 33,
           "name": "Eye on the Ball",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": 20,
           "wining": "Gift Hamper",
           "category": "FunGame",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 34,
           "name": "Gaming Mania",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "Solo:50/-& Squad:200",
           "wining": "500/- for Solo & 1500/- for Squad",
           "category": "technical",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 35,
           "name": "Dance Competition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "Solo:30/-,Duo:50/-& Squad:100",
           "wining": "500/- for (Solo & Duo) & 1000/- for Squad",
           "category": "Cultural",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 36,
           "name": "Singing Competition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "Solo:30/-,Duo:50/-& Squad:100",
           "wining": "500/- for (Solo & Duo) & 1000/- for Squad",
           "category": "Cultural",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 37,
           "name": "Poetry Competition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "30",
           "wining": "300/- ",
           "category": "Cultural",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 38,
           "name": "Stand-up Competition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "30",
           "wining": "300/- ",
           "category": "Cultural",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 39,
           "name": "Instrument Playing",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "30",
           "wining": "300/- ",
           "category": "Cultural",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       },
       {
           "id": 40,
           "name": "Mimicry Competition",
           "description": "description",
           "description1": "description1",
           "description2":"description2",
           "description3":"description3",
           "entry": "30",
           "wining": "300/- ",
           "category": "Cultural",
           "coordinator": "coordinator ",
           "coordinator1":"coordinator1",
           "coordinator2":"coordinator2",
           "coordinator3":"coordinator3",
           "register":"RegisterLink"
       }
   ]
